
node:
    #image: node
    build: ./node
    container_name: node_ldap
    volumes:
        - "/root/ldap/node/src/:/usr/src"
    ports:
        - 3000:3000
    #    - 4200:4200
    working_dir: "/usr/src/"
    #command: "/etc/start.sh"
    command: "npm start"
    #command: "ping localhost"
    links:
    - ldap
ldap:
    container_name: ldap
    build: ./ldap
    ports:
    - "389:389"
    volumes:
    - "/root/ldap/ldap/:/ldap/"